name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**'
#       '!orders/docs/**'     unless it is in the docs folder
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
